apiVersion: v1
kind: Pod
metadata:
  name: emaruya-nginx
  labels:
    app: emaruya-nginx     # funciona como uma tag para amarrar a outro recurso, geralmente coloca igual o nome
spec:
  containers:
    - name: container-pod-nginx
      image: nginx:latest
      ports:
        - containerPort: 80



apiVersion: v1
kind: Pod
metadata:
  name: emaruya-java
  labels:
    app: emaruya-java     # funciona como uma tag para amarrar a outro recurso, geralmente coloca igual o nome
spec:
  containers:
    - name: container-pod-java
      image: emaruya/validador-cpf-java-turma-devops:0.0.1
      ports:
        - containerPort: 8080

# kubectl apply -f pod-nginx.yml
# kubectl describe -f pod-nginx.yml
# kubectl delete -f pod-nginx.yml
