apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: java-replicaset
spec:
  template:
    metadata:
      name: emaruya-java
      labels:
        app: emaruya-java
    spec:
      containers:
        - name: container-pod-java-rs
          image: emaruya/validador-cpf-java-turma-devops:0.0.1
          ports:
            - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      app: emaruya-java


# $ kubectl logs -l app=lable-pod-java # log de todos os lables do replicaset
# $ kubectl logs --tail=20 --follow=true -l app=lable-pod-java